Deployments

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -49,7 +49,7 @@ jobs:
           ECR_URI=${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPOSITORY }}
           VERSION=${{ github.run_number }}
           for svc in frontend checkout payment recommendation email currency product-catalog shipping ad cart accounting fraud-detection quote image-provider load-generator flagd-ui kafka; do
-            echo "🔍 Scanning $svc..."
+            echo "Scanning $svc..."
             IMAGE=${ECR_URI}:${svc}-${VERSION}
             trivy image --exit-code 0 --severity HIGH,CRITICAL $IMAGE
           done
@@ -77,7 +77,7 @@ jobs:
       #     ECR_URI=${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPOSITORY }}
       #     FILE=k8s/07-deployments.yaml
       #      for svc in frontend checkout payment email currency product-catalog shipping ad cart accounting fraud-detection quote image-provider load-generator flagd-ui kafka; do
-      #       sed -i "s|image: .*${svc}.*|image: ${ECR_URI}:${svc}-${{ github.sha }}|" $FILE
+      #       sed -i "s|image: .*${svc}.*|image: ${ECR_URI}:${svc}-${{ github.run_number }}|" $FILE
       #     done
 
       #     sed -i "s|image: .*recommendation.*|image: ${ECR_URI}:recommendation-INVALIDTAG|" $FILE
@@ -94,8 +94,8 @@ jobs:
       - name: Rollback on failure
         if: failure()
         run: |
-          echo "🚨 Deployment failed. Rolling back to previous stable versions..."
+          echo "Deployment failed. Rolling back to previous stable versions..."
           for svc in frontend checkout payment recommendation email currency product-catalog shipping ad cart accounting fraud-detection quote image-provider load-generator flagd-ui kafka; do
-            echo "🔁 Rolling back $svc"
-            kubectl rollout undo deployment/$svc || echo "❗ Rollback failed for $svc (may not exist)"
+            echo "Rolling back $svc"
+            kubectl rollout undo deployment/$svc || echo "Rollback failed for $svc (may not exist)"
           done
